--------------------------------------------------------
--  文件已创建 - 星期六-一月-12-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CAR
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."CAR" 
   (	"ID" NUMBER(11,0), 
	"CAR_NUMBER" NVARCHAR2(255), 
	"BRAND" VARCHAR2(255 BYTE), 
	"DESCRIBE" VARCHAR2(255 BYTE), 
	"ID_NUMBER" VARCHAR2(255 BYTE), 
	"BUY_TIME" VARCHAR2(255 BYTE), 
	"DAILY_RENT" NUMBER(11,0), 
	"RENT_START_TIME" VARCHAR2(255 BYTE), 
	"RENT_DEAD_LINE" VARCHAR2(255 BYTE), 
	"PROFIT" NUMBER(11,0) DEFAULT 0, 
	"IS_NORMAL" VARCHAR2(20 BYTE) DEFAULT NULL, 
	"IS_RENT" VARCHAR2(20 CHAR)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
 

   COMMENT ON COLUMN "SYSTEM"."CAR"."CAR_NUMBER" IS '车辆的号牌';
 
   COMMENT ON COLUMN "SYSTEM"."CAR"."BRAND" IS '品牌';
 
   COMMENT ON COLUMN "SYSTEM"."CAR"."DESCRIBE" IS '描述信息';
 
   COMMENT ON COLUMN "SYSTEM"."CAR"."ID_NUMBER" IS '出租人身份证号码';
 
   COMMENT ON COLUMN "SYSTEM"."CAR"."BUY_TIME" IS '初次购买日期';
 
   COMMENT ON COLUMN "SYSTEM"."CAR"."DAILY_RENT" IS '日租金';
 
   COMMENT ON COLUMN "SYSTEM"."CAR"."RENT_START_TIME" IS '出租起始时间';
 
   COMMENT ON COLUMN "SYSTEM"."CAR"."RENT_DEAD_LINE" IS '出租截止时间';
 
   COMMENT ON COLUMN "SYSTEM"."CAR"."PROFIT" IS '盈利';
 
   COMMENT ON COLUMN "SYSTEM"."CAR"."IS_NORMAL" IS '是否是正常';
 
   COMMENT ON COLUMN "SYSTEM"."CAR"."IS_RENT" IS '是否出租';
REM INSERTING into SYSTEM.CAR
SET DEFINE OFF;
Insert into SYSTEM.CAR (ID,CAR_NUMBER,BRAND,DESCRIBE,ID_NUMBER,BUY_TIME,DAILY_RENT,RENT_START_TIME,RENT_DEAD_LINE,PROFIT,IS_NORMAL,IS_RENT) values (11,'挂B 24343','红旗','车况很好','45093323234234234',null,300,null,null,0,'正常','空闲');
Insert into SYSTEM.CAR (ID,CAR_NUMBER,BRAND,DESCRIBE,ID_NUMBER,BUY_TIME,DAILY_RENT,RENT_START_TIME,RENT_DEAD_LINE,PROFIT,IS_NORMAL,IS_RENT) values (12,'挂B 24323','红旗','车况很好','45093323234234234',null,400,null,null,0,'正常','空闲');
Insert into SYSTEM.CAR (ID,CAR_NUMBER,BRAND,DESCRIBE,ID_NUMBER,BUY_TIME,DAILY_RENT,RENT_START_TIME,RENT_DEAD_LINE,PROFIT,IS_NORMAL,IS_RENT) values (14,'挂B 2a343','红旗','车况很好','45068888888333332',null,500,null,null,0,'正常','出租中');
Insert into SYSTEM.CAR (ID,CAR_NUMBER,BRAND,DESCRIBE,ID_NUMBER,BUY_TIME,DAILY_RENT,RENT_START_TIME,RENT_DEAD_LINE,PROFIT,IS_NORMAL,IS_RENT) values (15,'挂B 2434q',null,'车辆增加速度1 not real','45068888888333332',null,null,null,null,null,null,null);
--------------------------------------------------------
--  DDL for Index CAR_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."CAR_PK" ON "SYSTEM"."CAR" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Trigger CAR_ID_AUTO
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "SYSTEM"."CAR_ID_AUTO" 
   before insert on "SYSTEM"."CAR" 
   for each row 
begin  
   if inserting then 
      if :NEW."ID" is null then 
         select ID_AUTO.nextval into :NEW."ID" from dual; 
      end if; 
   end if; 
end;

/
ALTER TRIGGER "SYSTEM"."CAR_ID_AUTO" ENABLE;
--------------------------------------------------------
--  Constraints for Table CAR
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."CAR" ADD CONSTRAINT "CAR_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "SYSTEM"."CAR" MODIFY ("CAR_NUMBER" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."CAR" MODIFY ("ID_NUMBER" NOT NULL ENABLE);
