--------------------------------------------------------
--  文件已创建 - 星期六-一月-12-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table RENT_CRED
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."RENT_CRED" 
   (	"ID" NUMBER(19,0), 
	"BRAND" VARCHAR2(255 CHAR), 
	"CAR_NUMBER" VARCHAR2(255 CHAR), 
	"COMPANY_NAME" VARCHAR2(255 CHAR), 
	"CRED_NUMBER" NUMBER(10,0), 
	"DAILY_RENT" NUMBER(10,0), 
	"DEPOSIT" NUMBER(10,0), 
	"PHONE_NUMBER" VARCHAR2(255 CHAR), 
	"PRE_DEAD_LINE" VARCHAR2(255 BYTE), 
	"RENT_AGENT_NUMBER" VARCHAR2(255 CHAR), 
	"RENT_START_TIME" VARCHAR2(255 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
 

   COMMENT ON COLUMN "SYSTEM"."RENT_CRED"."BRAND" IS '品牌';
 
   COMMENT ON COLUMN "SYSTEM"."RENT_CRED"."CAR_NUMBER" IS '车辆的号牌';
 
   COMMENT ON COLUMN "SYSTEM"."RENT_CRED"."COMPANY_NAME" IS '租赁公司名';
 
   COMMENT ON COLUMN "SYSTEM"."RENT_CRED"."CRED_NUMBER" IS '凭证号';
 
   COMMENT ON COLUMN "SYSTEM"."RENT_CRED"."DAILY_RENT" IS '日租金';
 
   COMMENT ON COLUMN "SYSTEM"."RENT_CRED"."DEPOSIT" IS '所交押金';
 
   COMMENT ON COLUMN "SYSTEM"."RENT_CRED"."PHONE_NUMBER" IS '电话';
 
   COMMENT ON COLUMN "SYSTEM"."RENT_CRED"."PRE_DEAD_LINE" IS '预期还车时间';
 
   COMMENT ON COLUMN "SYSTEM"."RENT_CRED"."RENT_AGENT_NUMBER" IS '出租经手人编号';
 
   COMMENT ON COLUMN "SYSTEM"."RENT_CRED"."RENT_START_TIME" IS '出租起始时间';
REM INSERTING into SYSTEM.RENT_CRED
SET DEFINE OFF;
Insert into SYSTEM.RENT_CRED (ID,BRAND,CAR_NUMBER,COMPANY_NAME,CRED_NUMBER,DAILY_RENT,DEPOSIT,PHONE_NUMBER,PRE_DEAD_LINE,RENT_AGENT_NUMBER,RENT_START_TIME) values (3,'红旗','挂B 2a343','科大租车',986,500,1000,'12345678',null,'4','2019-01-12 16:12:28');
Insert into SYSTEM.RENT_CRED (ID,BRAND,CAR_NUMBER,COMPANY_NAME,CRED_NUMBER,DAILY_RENT,DEPOSIT,PHONE_NUMBER,PRE_DEAD_LINE,RENT_AGENT_NUMBER,RENT_START_TIME) values (1,'1','1','1',1,1,1,'1','1','1','1');
Insert into SYSTEM.RENT_CRED (ID,BRAND,CAR_NUMBER,COMPANY_NAME,CRED_NUMBER,DAILY_RENT,DEPOSIT,PHONE_NUMBER,PRE_DEAD_LINE,RENT_AGENT_NUMBER,RENT_START_TIME) values (2,'红旗','挂B 24343','科大租车',1640,300,1000,'12345678',null,'4','2019-01-11 11:18:13');
--------------------------------------------------------
--  DDL for Index RENT_CRED_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."RENT_CRED_PK" ON "SYSTEM"."RENT_CRED" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Trigger RENT_CRED
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "SYSTEM"."RENT_CRED" 
   before insert on "SYSTEM"."RENT_CRED" 
   for each row 
begin  
   if inserting then 
      if :NEW."ID" is null then 
         select ID_AUTO.nextval into :NEW."ID" from dual; 
      end if; 
   end if; 
end;

/
ALTER TRIGGER "SYSTEM"."RENT_CRED" DISABLE;
--------------------------------------------------------
--  Constraints for Table RENT_CRED
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."RENT_CRED" ADD CONSTRAINT "RENT_CRED_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "SYSTEM"."RENT_CRED" MODIFY ("ID" NOT NULL ENABLE);
