--------------------------------------------------------
--  文件已创建 - 星期日-一月-13-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table REPAY_CRED
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."REPAY_CRED" 
   (	"ID" NUMBER(19,0), 
	"BRAND" VARCHAR2(255 CHAR), 
	"CAR_NUMBER" VARCHAR2(255 CHAR), 
	"CHANGE" NUMBER(10,0), 
	"COMPANY_NAME" VARCHAR2(255 CHAR), 
	"CRED_NUMBER" NUMBER(10,0), 
	"DAILY_RENT" NUMBER(10,0), 
	"DEPOSIT" NUMBER(10,0), 
	"DEPOSIT_REFUND" NUMBER(10,0), 
	"PAY_AMOUNT" VARCHAR2(255 CHAR), 
	"RENT_DEAD_LINE" VARCHAR2(255 BYTE), 
	"THE_RENT" NUMBER(10,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
 

   COMMENT ON COLUMN "SYSTEM"."REPAY_CRED"."BRAND" IS '品牌';
 
   COMMENT ON COLUMN "SYSTEM"."REPAY_CRED"."CAR_NUMBER" IS '车辆的号牌';
 
   COMMENT ON COLUMN "SYSTEM"."REPAY_CRED"."CHANGE" IS '找零';
 
   COMMENT ON COLUMN "SYSTEM"."REPAY_CRED"."COMPANY_NAME" IS '租赁公司名';
 
   COMMENT ON COLUMN "SYSTEM"."REPAY_CRED"."CRED_NUMBER" IS '凭证号';
 
   COMMENT ON COLUMN "SYSTEM"."REPAY_CRED"."DAILY_RENT" IS '日租金';
 
   COMMENT ON COLUMN "SYSTEM"."REPAY_CRED"."DEPOSIT" IS '所交押金';
 
   COMMENT ON COLUMN "SYSTEM"."REPAY_CRED"."DEPOSIT_REFUND" IS '押金退还';
 
   COMMENT ON COLUMN "SYSTEM"."REPAY_CRED"."PAY_AMOUNT" IS '补交金额';
 
   COMMENT ON COLUMN "SYSTEM"."REPAY_CRED"."RENT_DEAD_LINE" IS '还车时间';
 
   COMMENT ON COLUMN "SYSTEM"."REPAY_CRED"."THE_RENT" IS '租金';
REM INSERTING into SYSTEM.REPAY_CRED
SET DEFINE OFF;
Insert into SYSTEM.REPAY_CRED (ID,BRAND,CAR_NUMBER,CHANGE,COMPANY_NAME,CRED_NUMBER,DAILY_RENT,DEPOSIT,DEPOSIT_REFUND,PAY_AMOUNT,RENT_DEAD_LINE,THE_RENT) values (62,'红旗','挂B 2a343',-1000,'科大租车',710,500,1000,1000,'-1000','2019-01-28 09:14:16',0);
Insert into SYSTEM.REPAY_CRED (ID,BRAND,CAR_NUMBER,CHANGE,COMPANY_NAME,CRED_NUMBER,DAILY_RENT,DEPOSIT,DEPOSIT_REFUND,PAY_AMOUNT,RENT_DEAD_LINE,THE_RENT) values (61,'1','1',1,'1',1,1,1,1,'1','1',1);
--------------------------------------------------------
--  DDL for Index REPAY_CRED_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."REPAY_CRED_PK" ON "SYSTEM"."REPAY_CRED" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Trigger REPAY_CRED
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "SYSTEM"."REPAY_CRED" 
   before insert on "SYSTEM"."REPAY_CRED" 
   for each row 
begin  
   if inserting then 
      if :NEW."ID" is null then 
         select ID_AUTO.nextval into :NEW."ID" from dual; 
      end if; 
   end if; 
end;

/
ALTER TRIGGER "SYSTEM"."REPAY_CRED" ENABLE;
--------------------------------------------------------
--  Constraints for Table REPAY_CRED
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."REPAY_CRED" ADD CONSTRAINT "REPAY_CRED_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
